version: '3'
services:
    db:
        image: postgres
        volumes: 
            - "prayNmeetdb:/var/lib/postgres/data/"
        environment:
            - POSTGRES_DB=prayNmeetdb 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5433:5432"
    web:
        build: .
        command: python manage.py run -h 0.0.0.0
        volumes: 
            - "./prayNmeet:/app"
        env_file: 
            - .env
        ports:
            - "5000:5000"
        depends_on: 
            - db    
volumes: 
    prayNmeetdb:
